### PR TITLE
feat: sync llama.cpp

### LINKED ISSUE #77: RWKV support (sync llama.cpp)
Llama.cpp added support for RWKV models in https://github.com/ggerganov/llama.cpp/releases/tag/b3651
Can you sync the version llama.rn uses so that we can try those models? They are very lightweight and need a lot less RAM than transformers models, so it's a great fit for mobile devices.

### PR DESCRIPTION
**Pull request by a-ghorbani**
Sync `llama.cpp` with the [b3972](https://github.com/ggerganov/llama.cpp/releases/tag/b3972) release.

This will close #77.

### CODE REVIEW

**Comment by a-ghorbani** [comment]
I’m almost done, just running the final tests.
Mostly based on @Vali-98's work: https://github.com/Vali-98/cui-llama.rn

@Vali-98 , if you have a moment, a quick review would be much appreciated to catch anything I might have missed!

**Comment by Vali-98** [comment]
It looks okay from a glance, can't confirm for the IOS code though.

Just to confirm, I applied changes for cui-llama.rn from my fork of llama.cpp: https://github.com/Vali-98/llama.cpp/tree/cui-llama.rn

The current method of patching changes to llama.rn is the main reason why I wanted my own fork instead, as patching the files tends to fail spectacularly when syncing llama.cpp. I assume this is the reason why the CI is failing too.

Ideally for release builds, we would include prebuilt binaries instead of needing to build llama.cpp redundantly every time.

**Comment by Vali-98** [comment]
You might want to mention that this adds the `vocab_only` field as it isn't actually a part of `gpt_params` on llama.cpp.

**Comment by jhen0409** [comment]
This is awesome, thanks for the contribution!

It looks like `n_gpu_layers = 0` for disable GPU is broken (see https://github.com/ggerganov/llama.cpp/issues/10089), I'll checkout for that before merge this.

**Pull request merged**
