### PR TITLE
fix(android): some unicode characters not working

### PR DESCRIPTION
**Pull request by SlackCrow**
The original code was using NewStringUTF which caused the app to crash when certain unicode characters, such as emojis, were used. 

So instead I added a helper function that converts the UTF-8 input into jstring manually.

### CODE REVIEW

**Comment by jhen0409** [comment]
Hi, thank you for the PR!

I can see the correctly completion result, but it got unexpected result in the partial token event. We already handled with waiting 2-4 bytes and send token event:

https://github.com/mybigday/llama.rn/blob/4c90a78e562732ddf6e07d064241254c212656d6/cpp/rn-llama.hpp#L464-L482

It would be great if you could check this problem out, I'll do so when I available.

**Comment by SlackCrow** [comment]
Could you elaborate what you meant by partial token events? It might be due to the function I wrote not having a lot of error handlings for invalid UTF-8 characters. I didn't include it because as far as I know llama.cpp treats all token values as unicode, but I could be wrong.

**Comment by jhen0409** [comment]
> Could you elaborate what you meant by partial token events?

This:
https://github.com/mybigday/llama.rn/blob/4c90a78e562732ddf6e07d064241254c212656d6/android/src/main/jni.cpp#L436-L465

Our [example](https://github.com/mybigday/llama.rn/blob/4c90a78e562732ddf6e07d064241254c212656d6/example/src/App.tsx#L346-L374) also use it.

**Comment by jhen0409** [comment]
3799cf8 should fix the unicode issue and the issue about partial event, so this handle may not be need. Still thank you for the PR!

**Comment by SlackCrow** [comment]
No problem, thank you for fixing the code! I was a bit busy last few days and couldn't really check it.

**Pull request closed without merging**
